In [1]:
import pandas as pd
import xml.etree.ElementTree as ET
from entsoe import EntsoePandasClient
from entsoe import EntsoeRawClient
from entsoe_queries.queries import query_aFRR_CBMPs

# Your ENTSO-E API token
your_api_key = '48b89f4f-eb82-4315-b0c5-ca95e1185554'

# Client for Easy Queries
client_pd = EntsoePandasClient(api_key=your_api_key)
client_raw = EntsoeRawClient(api_key=your_api_key)

# Define the parameters for the query
country_code = 'CH'  # Switzerland

start = pd.Timestamp('2024-05-15 00:00:00', tz='Europe/Brussels')
end = pd.Timestamp('2024-07-31 00:00:00', tz='Europe/Brussels')
imbalance_prices  = client_pd.query_imbalance_prices(country_code, start=start, end=end).tz_localize(None)
imbalance_prices

                      Long  Short
2024-05-15 00:00:00  -10.3  138.7
2024-05-15 00:15:00    8.2   95.4
2024-05-15 00:30:00   -3.2   85.1
2024-05-15 00:45:00  -19.8   74.9
2024-05-15 01:00:00    0.7   96.3
...                    ...    ...
2024-07-30 22:45:00  -47.9  124.5
2024-07-30 23:00:00  -31.2  628.6
2024-07-30 23:15:00  -22.3  303.2
2024-07-30 23:30:00  -48.2  151.1
2024-07-30 23:45:00 -100.2   64.9

[7392 rows x 2 columns]

In [ ]:
prices_fr = client_pd.query_activated_balancing_energy_prices(
    country_code='FR',
    start=pd.Timestamp("2025-06-10", tz='Europe/Paris'),
    end=pd.Timestamp("2025-06-11", tz='Europe/Paris'),
)
prices_fr

                          Direction   Price ReserveType
2025-06-10 00:00:00+02:00        Up   38.39         FCR
2025-06-10 00:00:00+02:00      Down   38.39         FCR
2025-06-10 00:00:00+02:00        Up   86.65          RR
2025-06-10 00:00:00+02:00        Up   84.31        mFRR
2025-06-10 00:00:00+02:00      Down   86.65          RR
...                             ...     ...         ...
2025-06-10 23:45:00+02:00        Up   72.38          RR
2025-06-10 23:45:00+02:00      Down   61.63         FCR
2025-06-10 23:45:00+02:00        Up   61.63         FCR
2025-06-10 23:45:00+02:00      Down   72.38          RR
2025-06-10 23:45:00+02:00        Up  271.31          RR

[479 rows x 3 columns]

In [3]:
prices_fr.ReserveType.unique()

array(['FCR', 'RR', 'mFRR'], dtype=object)

In [4]:
from datetime import datetime
import pytz

# Initialize client and define UTC time window
start = pd.Timestamp("2025-06-16T00:00:00Z")
end   = pd.Timestamp("2025-06-16T00:59:59Z")

df = query_aFRR_CBMPs(client_raw, start, end)
df

,PeriodStart,PeriodEnd,Direction,Price_EUR_per_MWh,LFC_Area
0,2025-06-16 00:00:00+00:00,2025-06-16 00:00:04+00:00,Down,6.70,10YFR-RTE------C
1,2025-06-16 00:00:04+00:00,2025-06-16 00:00:08+00:00,Down,6.70,10YFR-RTE------C
2,2025-06-16 00:00:08+00:00,2025-06-16 00:00:12+00:00,Down,13.12,10YFR-RTE------C
3,2025-06-16 00:00:12+00:00,2025-06-16 00:00:16+00:00,Down,13.12,10YFR-RTE------C
4,2025-06-16 00:00:16+00:00,2025-06-16 00:00:20+00:00,Down,13.12,10YFR-RTE------C
...,...,...,...,...,...
890,2025-06-16 00:59:20+00:00,2025-06-16 00:59:24+00:00,Down,33.94,10YFR-RTE------C
891,2025-06-16 00:59:24+00:00,2025-06-16 00:59:28+00:00,Down,33.94,10YFR-RTE------C
892,2025-06-16 00:59:28+00:00,2025-06-16 00:59:32+00:00,Down,33.94,10YFR-RTE------C
893,2025-06-16 00:59:32+00:00,2025-06-16 00:59:36+00:00,Down,33.94,10YFR-RTE------C
894,2025-06-16 00:59:36+00:00,2025-06-16 00:59:40+00:00,Down,43.17,10YFR-RTE------C